const filters = [
    "animal",
    "beach",
    "clouds",
    "dew",
    "dry leaves",
    "forest",
    "grass",
    "ice",
    "leaves",
    "ocean",
    "rocks",
    "sea",
    "snow",
    "stream",
    "sun",
    "sunset",
    "trees",
    "water",
    "waterfalls",
    "wet leaves",
];

const gallery = [
    {
        src: "https://i.postimg.cc/ZRyzkYN1/pexels-eberhard-grossgasteiger-2310641.jpg",
        alt: "A field with trees and brown leaves",
        category: "autumn",
        filters: ["trees"],
    },
    {
        src: "https://i.postimg.cc/k5sBVchn/pexels-irina-iriser-1590549.jpg",
        alt: "Brown leaves hanging from a tree",
        category: "autumn",
        filters: ["leaves", "sun"],
    },
    {
        src: "https://i.postimg.cc/DwHKxbJq/pexels-jara-3083250.jpg",
        alt: "Wet fallen leaves",
        category: "autumn",
        filters: ["leaves", "dew", "water", "wet leaves"],
    },
    {
        src: "https://i.postimg.cc/J0L4ssCW/pexels-josh-hild-14269090.jpg",
        alt: "A dog in a bush with dry grasses",
        category: "autumn",
        filters: ["animal", "grass"],
    },
    {
        src: "https://i.postimg.cc/Jn7pMqGw/pexels-lil-artsy-3127729.jpg",
        alt: "A cat standing beside the road with fallen maple leaves",
        category: "autumn",
        filters: ["animal", "leaves", "dry leaves"],
    },
    {
        src: "https://i.postimg.cc/K8JNQT0J/pexels-lisa-fotios-2812164.jpg",
        alt: "A forest with tall trees and dead leaves",
        category: "autumn",
        filters: ["forest", "trees"],
    },
    {
        src: "https://i.postimg.cc/4yQtyCMB/pexels-luke-barky-2899722.jpg",
        alt: "A field with grass, fenced with a rope tied to poles",
        category: "autumn",
        filters: ["sunset", "grass"],
    },
    {
        src: "https://i.postimg.cc/Vs2LrH1F/pexels-maro-markovi-1468735.jpg",
        alt: "A narrow stream, flowing from rocks with fallen leaves around it",
        category: "autumn",
        filters: ["stream", "rocks", "wet leaves"],
    },
    {
        src: "https://i.postimg.cc/9MG1dnKq/pexels-petar-star-evi-2389122.jpg",
        alt: "A field with dried grass and rolled up barn",
        category: "autumn",
        filters: ["field", "grass"],
    },
    {
        src: "https://i.postimg.cc/tJv6Wdqx/pexels-ylanite-koppens-612816.jpg",
        alt: "Dried acorns and leaves",
        category: "autumn",
        filters: ["leaves"],
    },
    {
        src: "https://i.postimg.cc/9fPqJHXV/pexels-afr-creation-15994490.jpg",
        alt: "Wet leaf with water drops",
        category: "spring",
        filters: ["water", "leaves", "wet leaves"],
    },
    {
        src: "https://i.postimg.cc/y6p3fPKJ/pexels-andreas-15985749.jpg",
        alt: "A field with trees and green grass",
        category: "spring",
        filters: ["trees", "grass", "field"],
    },
    {
        src: "https://i.postimg.cc/8Cnsyk82/pexels-david-brown-16001827.jpg",
        alt: "Bread resting on a tree branch while it drizzles",
        category: "spring",
        filters: ["water", "animal"],
    },
    {
        src: "https://i.postimg.cc/7YQcYpkx/pexels-denniz-futalan-5049271.jpg",
        alt: "A rabbit in a bush with green grasses",
        category: "spring",
        filters: ["animal", "grass", "leaves"],
    },
    {
        src: "https://i.postimg.cc/286ktRGm/pexels-dids-4261738.jpg",
        alt: "A wet leaf",
        category: "spring",
        filters: ["water", "leaves", "wet leaves"],
    },
    {
        src: "https://i.postimg.cc/Xvgt3XNP/pexels-jonathan-petersson-1076183.jpg",
        alt: "Sunset in a forest with tall trees and green grass",
        category: "spring",
        filters: ["trees", "grass"],
    },
    {
        src: "https://i.postimg.cc/SQzFYSgn/pexels-maria-orlova-4906295.jpg",
        alt: "Blossoming flowers on a tree against clear blue sky",
        category: "spring",
        filters: ["leaves", "flowers"],
    },
    {
        src: "https://i.postimg.cc/3xZdMCpQ/pexels-pixabay-40731.jpg",
        alt: "Lady bug on a blade of grass wet with dew",
        category: "spring",
        filters: ["grass", "water", "wet leaves", "animal"],
    },
    {
        src: "https://i.postimg.cc/zvDxjknD/pexels-pixabay-86431.jpg",
        alt: "A field with grass and blossoming red flowers",
        category: "spring",
        filters: ["flowers", "field", "grass", "clouds"],
    },
    {
        src: "https://i.postimg.cc/2SjBSKCS/pexels-q-h-ng-ph-m-15962267.jpg",
        alt: "Flowers on tree branches",
        category: "spring",
        filters: ["trees", "flowers"],
    },
    {
        src: "https://i.postimg.cc/cL6wcb25/pexels-asad-photo-maldives-3601421.jpg",
        alt: "Beach houses on the sea",
        category: "summer",
        filters: ["sunset", "water", "sea"],
    },
    {
        src: "https://i.postimg.cc/tCcY9Cv2/pexels-dom-gould-325807.jpg",
        alt: "Stream in the middle of rocks and trees",
        category: "summer",
        filters: ["trees", "rocks", "water"],
    },
    {
        src: "https://i.postimg.cc/GpxLTcz0/pexels-james-wheeler-1486974.jpg",
        alt: "Sunset with clear clouds reflecting on a lake",
        category: "summer",
        filters: ["trees", "grass", "water", "clouds"],
    },
    {
        src: "https://i.postimg.cc/Wbqs6mSw/pexels-partha-chatterjee-16070595.jpg",
        alt: "Sunflowers",
        category: "summer",
        filters: ["flowers"],
    },
    {
        src: "https://i.postimg.cc/Kcw2zkFk/pexels-pixabay-262713.jpg",
        alt: "Sun shining on a field of flowers",
        category: "summer",
        filters: ["flowers", "field"],
    },
    {
        src: "https://i.postimg.cc/pL2RbNRq/pexels-pixabay-302549.jpg",
        alt: "Trees growing on a rock in the sea",
        category: "summer",
        filters: ["rocks", "trees", "water"],
    },
    {
        src: "https://i.postimg.cc/gjVFQs7C/pexels-pixabay-358457.jpg",
        alt: "A waterfall above a bridge",
        category: "summer",
        filters: ["waterfalls", "rocks", "trees"],
    },

    {
        src: "https://i.postimg.cc/rF929hxW/pexels-roberto-nickson-2631613.jpg",
        alt: "A beach with palm trees and shelters",
        category: "summer",
        filters: ["field", "grass", "trees", "rocks"],
    },
    {
        src: "https://i.postimg.cc/RhQyXF69/pexels-robert-so-15968083.jpg",
        alt: "A clear sky above a field with a tree and green grass",
        category: "summer",
        filters: ["beach", "trees", "ocean", "water"],
    },
    {
        src: "https://i.postimg.cc/W4k953CK/pexels-ryan-delfin-2270389.jpg",
        alt: "Tall palm trees",
        category: "summer",
        filters: ["clouds", "trees"],
    },
    {
        src: "https://i.postimg.cc/dQphYVxn/pexels-alissa-nabiullina-997567.jpg",
        alt: "Flower seeds on a tree covered with snow",
        category: "winter",
        filters: ["snow", "flowers"],
    },
    {
        src: "https://i.postimg.cc/PqSbHv9N/pexels-annika-thierfeld-735986.jpg",
        alt: "A deer in the snow",
        category: "winter",
        filters: ["snow", "animal", "trees"],
    },
    {
        src: "https://i.postimg.cc/65zpYVv7/pexels-eberhard-grossgasteiger-1366919.jpg",
        alt: "A mountain partially covered with snow",
        category: "winter",
        filters: ["snow", "rocks"],
    },
    {
        src: "https://i.postimg.cc/nr2pSZC8/pexels-eberhard-grossgasteiger-1417651.jpg",
        alt: "Mountain under a night sky with snow falling",
        category: "winter",
        filters: ["field", "rocks", "snow"],
    },
    {
        src: "https://i.postimg.cc/0jBHyH4M/pexels-egor-kamelev-813872.jpg",
        alt: "A snowflake on grass",
        category: "winter",
        filters: ["ice", "flowers", "grass"],
    },
    {
        src: "https://i.postimg.cc/1t6j3HQJ/pexels-julia-volk-5111048.jpg",
        alt: "An iceberg",
        category: "winter",
        filters: ["ice", "snow", "water"],
    },
    {
        src: "https://i.postimg.cc/sXpH1zLG/pexels-nikolai-ulltang-325139.jpg",
        alt: "A river surrounded by trees with snow on them",
        category: "winter",
        filters: ["trees", "water"],
    },
    {
        src: "https://i.postimg.cc/k5w5hxZY/pexels-pixabay-86405.jpg",
        alt: "A penguin in the snow",
        category: "winter",
        filters: ["ice", "snow", "animal"],
    },
    {
        src: "https://i.postimg.cc/fyF43bPv/pexels-rok-romih-3894112.jpg",
        alt: "A bird flying while it snows",
        category: "winter",
        filters: ["animal", "snow"],
    },
    {
        src: "https://i.postimg.cc/yYtgKXLD/pexels-simon-berger-3732527.jpg",
        alt: "A tree with frozen branches",
        category: "winter",
        filters: ["trees", "snow"],
    },
];

export { filters, gallery };
